services:
  customer-api:
    container_name: customer-api
    build:
      dockerfile: Dockerfile
      context: .
      target: production
    volumes:
      - .:/usr/src/app
    env_file:
    - .env
    command: npm run start:prod
    ports:
      - 3000:3000

  redis:
    container_name: redis
    image: redis:alpine
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data

volumes:
  redis-data:
    driver: local
